import { useState } from 'react';
import { estimateTco } from './api';
import { TcoResult } from './types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import './App.css';

function App() {
  const [make, setMake] = useState('');
  const [model, setModel] = useState('');
  const [year, setYear] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<TcoResult | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const data = await estimateTco({
        make,
        model,
        year: parseInt(year),
      });
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'ILS',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const formatTrigger = (item: any) => {
    const parts = [];
    if (item.trigger.km) parts.push(`${item.trigger.km.toLocaleString()} km`);
    if (item.trigger.ageYears) parts.push(`${item.trigger.ageYears} years`);
    return parts.join(' / ') || 'N/A';
  };

  const formatWindow = (window: any) => {
    const parts = [];
    if (window.kmMin && window.kmMax) {
      parts.push(`${window.kmMin.toLocaleString()}-${window.kmMax.toLocaleString()} km`);
    }
    if (window.ageMin && window.ageMax) {
      parts.push(`${window.ageMin}-${window.ageMax} years`);
    }
    return parts.join(' or ') || 'N/A';
  };

  const exportToPDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Title
    doc.setFontSize(18);
    doc.setTextColor(37, 99, 235);
    doc.text('Car Lifetime TCO Report', pageWidth / 2, 20, { align: 'center' });
    
    // Vehicle Info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`${year} ${make} ${model}`, pageWidth / 2, 30, { align: 'center' });
    
    // Confidence Badge
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Overall Confidence: ${result.overallConfidence.toUpperCase()}`, pageWidth / 2, 37, { align: 'center' });
    
    // Summary Section
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Summary', 14, 50);
    
    autoTable(doc, {
      startY: 55,
      head: [['Metric', 'Value']],
      body: [
        ['Total Lifetime Cost', formatCurrency(result.lifetime.totalCost)],
        ['Cost Per Month', formatCurrency(result.lifetime.costPerMonth)],
        ['Duration', `${result.lifetime.months} months`],
        ['End Reason', result.lifetime.endReason === 'maxYears' ? 'Max age reached' : 'Max km reached'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
    });

    // Breakdown Section
    const finalY1 = (doc as any).lastAutoTable.finalY || 85;
    doc.text('Cost Breakdown', 14, finalY1 + 10);
    
    autoTable(doc, {
      startY: finalY1 + 15,
      head: [['Category', 'Amount']],
      body: [
        ['Depreciation', formatCurrency(result.breakdown.depreciation)],
        ['Fuel', formatCurrency(result.breakdown.fuel)],
        ['Maintenance', formatCurrency(result.breakdown.maintenance)],
        ['Fees', formatCurrency(result.breakdown.fees)],
      ],
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
    });

    // Timeline Section
    const finalY2 = (doc as any).lastAutoTable.finalY || 125;
    
    // Check if we need a new page
    if (finalY2 > 240) {
      doc.addPage();
      doc.text('Timeline Events', 14, 20);
    } else {
      doc.text('Timeline Events', 14, finalY2 + 10);
    }
    
    const timelineData = result.timeline.map(item => [
      item.item,
      item.category,
      formatTrigger(item),
      formatCurrency(item.cost.mid),
      item.confidence,
    ]);

    autoTable(doc, {
      startY: finalY2 > 240 ? 25 : finalY2 + 15,
      head: [['Item', 'Category', 'Trigger', 'Est. Cost', 'Confidence']],
      body: timelineData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 30 },
        2: { cellWidth: 35 },
        3: { cellWidth: 30 },
        4: { cellWidth: 25 },
      },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by Car TCO Calculator - Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    // Save
    doc.save(`TCO_${year}_${make}_${model}.pdf`);
  };

  const exportToExcel = () => {
    if (!result) return;

    const workbook = XLSX.utils.book_new();

    // Summary Sheet
    const summaryData = [
      ['Car Lifetime TCO Report'],
      ['Vehicle', `${year} ${make} ${model}`],
      ['Overall Confidence', result.overallConfidence],
      [],
      ['Summary'],
      ['Total Lifetime Cost', result.lifetime.totalCost],
      ['Cost Per Month', result.lifetime.costPerMonth],
      ['Duration (months)', result.lifetime.months],
      ['End Reason', result.lifetime.endReason],
      [],
      ['Cost Breakdown'],
      ['Depreciation', result.breakdown.depreciation],
      ['Fuel', result.breakdown.fuel],
      ['Maintenance', result.breakdown.maintenance],
      ['Fees', result.breakdown.fees],
      ['Total', result.lifetime.totalCost],
    ];
    
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    
    // Style the summary sheet
    summarySheet['!cols'] = [{ wch: 25 }, { wch: 20 }];
    
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // Timeline Sheet
    const timelineData = [
      ['Item', 'Category', 'Trigger (km)', 'Trigger (years)', 'Cost Low', 'Cost Mid', 'Cost High', 'Confidence', 'Description', 'Notes'],
    ];
    
    result.timeline.forEach(item => {
      timelineData.push([
        item.item,
        item.category,
        item.trigger.km?.toString() || '',
        item.trigger.ageYears?.toString() || '',
        item.cost.low.toString(),
        item.cost.mid.toString(),
        item.cost.high.toString(),
        item.confidence,
        item.description,
        item.notes.join('; '),
      ]);
    });
    
    const timelineSheet = XLSX.utils.aoa_to_sheet(timelineData);
    
    // Column widths
    timelineSheet['!cols'] = [
      { wch: 30 }, // Item
      { wch: 15 }, // Category
      { wch: 12 }, // Trigger km
      { wch: 12 }, // Trigger years
      { wch: 12 }, // Cost Low
      { wch: 12 }, // Cost Mid
      { wch: 12 }, // Cost High
      { wch: 12 }, // Confidence
      { wch: 40 }, // Description
      { wch: 50 }, // Notes
    ];
    
    XLSX.utils.book_append_sheet(workbook, timelineSheet, 'Timeline');

    // Audit Sheet
    const auditData = [
      ['Audit Information'],
      ['Timeline Sorted', result.audit.timelineSorted ? 'Yes' : 'No'],
      ['Totals Consistent', result.audit.totalsConsistent ? 'Yes' : 'No'],
      ['Maintenance Matches Timeline', result.audit.maintenanceMatchesTimelineMid ? 'Yes' : 'No'],
      [],
      ['Flags'],
      ...result.audit.flags.map(flag => [flag]),
    ];
    
    const auditSheet = XLSX.utils.aoa_to_sheet(auditData);
    auditSheet['!cols'] = [{ wch: 35 }, { wch: 15 }];
    
    XLSX.utils.book_append_sheet(workbook, auditSheet, 'Audit');

    // Save
    XLSX.writeFile(workbook, `TCO_${year}_${make}_${model}.xlsx`);
  };

  return (
    <div className="app">
      <header>
        <h1>🚗 Car Lifetime TCO Calculator</h1>
        <p>Estimate the total cost of ownership for your vehicle</p>
      </header>

      <div className="container">
        <form onSubmit={handleSubmit} className="input-form">
          <div className="form-group">
            <label htmlFor="make">Make</label>
            <input
              id="make"
              type="text"
              value={make}
              onChange={(e) => setMake(e.target.value)}
              placeholder="e.g., Honda"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="model">Model</label>
            <input
              id="model"
              type="text"
              value={model}
              onChange={(e) => setModel(e.target.value)}
              placeholder="e.g., Civic"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="year">Year</label>
            <input
              id="year"
              type="number"
              value={year}
              onChange={(e) => setYear(e.target.value)}
              placeholder="e.g., 2016"
              min="2005"
              max="2026"
              required
            />
          </div>

          <button type="submit" disabled={loading} className="estimate-btn">
            {loading ? 'Calculating...' : 'Estimate TCO'}
          </button>
        </form>

        {error && (
          <div className="error-box">
            <strong>Error:</strong> {error}
          </div>
        )}

        {result && (
          <div className="results">
            <div className="result-header">
              <h2>
                {year} {make} {model}
              </h2>
              <div className="header-actions">
                <span className={`confidence confidence-${result.overallConfidence}`}>
                  {result.overallConfidence.toUpperCase()} CONFIDENCE
                </span>
                <div className="export-buttons">
                  <button onClick={exportToPDF} className="export-btn export-pdf">
                    📄 Export PDF
                  </button>
                  <button onClick={exportToExcel} className="export-btn export-excel">
                    📊 Export Excel
                  </button>
                </div>
              </div>
            </div>

            <div className="summary-cards">
              <div className="card">
                <div className="card-label">Total Lifetime Cost</div>
                <div className="card-value">
                  {formatCurrency(result.lifetime.totalCost)}
                </div>
              </div>
              <div className="card">
                <div className="card-label">Cost Per Month</div>
                <div className="card-value">
                  {formatCurrency(result.lifetime.costPerMonth)}
                </div>
              </div>
              <div className="card">
                <div className="card-label">Duration</div>
                <div className="card-value">
                  {result.lifetime.months} months
                </div>
                <div className="card-sublabel">
                  ({result.lifetime.endReason === 'maxYears' ? 'Max age reached' : 'Max km reached'})
                </div>
              </div>
              <div className="card">
                <div className="card-label">Timeline Events</div>
                <div className="card-value">
                  {result.timeline.length}
                </div>
              </div>
            </div>

            <div className="breakdown">
              <h3>Cost Breakdown</h3>
              <table>
                <tbody>
                  <tr>
                    <td>Depreciation</td>
                    <td>{formatCurrency(result.breakdown.depreciation)}</td>
                  </tr>
                  <tr>
                    <td>Fuel</td>
                    <td>{formatCurrency(result.breakdown.fuel)}</td>
                  </tr>
                  <tr>
                    <td>Maintenance</td>
                    <td>{formatCurrency(result.breakdown.maintenance)}</td>
                  </tr>
                  <tr>
                    <td>Fees (Registration, Taxes)</td>
                    <td>{formatCurrency(result.breakdown.fees)}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div className="timeline-section">
              <h3>Cost Timeline with Uncertainty Ranges</h3>
              <p className="timeline-subtitle">Expected maintenance and repairs over the vehicle's lifetime</p>
              
              {result.audit.flags.length > 0 && (
                <div className="audit-flags">
                  <strong>⚠️ Audit Notes:</strong>
                  <ul>
                    {result.audit.flags.map((flag, idx) => (
                      <li key={idx}>{flag}</li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="timeline-container">
                {result.timeline.map((item, idx) => (
                  <div key={idx} className={`timeline-event category-${item.category}`}>
                    <div className="event-marker">
                      <div className="event-dot"></div>
                      {idx < result.timeline.length - 1 && <div className="event-line"></div>}
                    </div>
                    <div className="event-content">
                      <div className="event-header">
                        <span className="event-item-name">{item.item}</span>
                        <span className={`event-category ${item.category}`}>
                          {item.category.replace('-', ' ')}
                        </span>
                      </div>
                      <div className="event-trigger">
                        <strong>Trigger:</strong> {formatTrigger(item)}
                      </div>
                      {(item.window.kmMin || item.window.ageMin) && (
                        <div className="event-window">
                          <strong>Window:</strong> {formatWindow(item.window)}
                        </div>
                      )}
                      <div className="event-description">{item.description}</div>
                      <div className="event-cost-range">
                        <div className="cost-range-label">Cost Range:</div>
                        <div className="cost-range-values">
                          <span className="cost-low">Low: {formatCurrency(item.cost.low)}</span>
                          <span className="cost-mid">Mid: {formatCurrency(item.cost.mid)}</span>
                          <span className="cost-high">High: {formatCurrency(item.cost.high)}</span>
                        </div>
                      </div>
                      <div className="event-meta">
                        <span className={`event-confidence confidence-${item.confidence}`}>
                          {item.confidence} confidence
                        </span>
                      </div>
                      {item.notes && item.notes.length > 0 && (
                        <div className="event-notes">
                          <ul>
                            {item.notes.map((note, noteIdx) => (
                              <li key={noteIdx}>{note}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      <footer>
        <p>
          ⚠️ Results are AI-generated estimates using expert automotive knowledge.
          Cost ranges represent realistic uncertainty. Actual costs may vary based on usage, location, and vehicle condition.
        </p>
      </footer>
    </div>
  );
}

export default App;
